name: C/C++ CI

on:
  push:
    branches: [ edg-6.8 ]
  pull_request:
    branches: [ edg-6.8 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y liblz4-dev
        mkdir build
    - name: Build
      run: |
        cmake ..
        make -j`nproc`
      working-directory: build
    - name: Test
      run: ctest -j`nproc`
      working-directory: build